name: HealthyTwerking
version: ${project.version}
main: me.infiware.healthytwerking.HealthyTwerking
api-version: 1.16
authors: [ Infiware ]
description: Minecraft, but Twerking heals you
commands:
  supertwerk:
    description: changes value of heal when shifting to 2.5
    usage: /<command>
  sadtwerk:
    description: changes value of heal when shifting to 0.5
    usage: /<command>
  normaltwerk:
    description: changes value of heal when shifting to 1.0
    usage: /<command>
  extremetwerk:
    description: changes value of heal when shifting to 10.0
    usage: /<command>
  notwerk:
    description: changes value of heal when shifting to 0.0
    usage: /<command>
