name: HealthyTwerking
version: ${project.version}
main: me.infiware.healthytwerking.HealthyTwerking
api-version: 1.16
authors: [ Infiware ]
description: Minecraft, but Twerking heals you
commands:
  twerkHealth:
    description: changes value of heal when shifting by the amount decided by the player
    usage: /<command> <double>
  notwerk:
    description: disables twerk healing
    usage: /<command>
