defaultTwerkDelay: 0
# this value must be a positive integer

defaultTwerkHealth: 1.0
# this value must be a double (a double is a decimal number

disableTwerkConfigCommands: 1
# this value must be 1 or 2 or else this will be defaulted to 1 (false = 1 and true = 2)