name: HealthyTwerking
version: 0.4
main: me.infiware.healthytwerking.HealthyTwerking
api-version: 1.16
authors: [ Infiware ]
description: Minecraft, but Twerking heals you
commands:
  twerkHealth:
    description: changes value of heal when shifting by the amount decided by the player
    usage: /<command> <double>
  noTwerk:
    description: disables twerk healing
    usage: /<command>
  twerkDelay:
    description: changes time of delay of times shifted to heal
    usage: /<command> <double>
